language: ruby
rvm: 2.3.3
cache:
  bundler: true
  directories:
  - node_modules
branches:
  only:
  - master
before_install:
- nvm install 7.4.0
install:
- npm install
- bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
before_script:
- git config --global user.name "hnbot"
- git config --global user.email "nygrenh+hnbot@gmail.com"
- export COMMIT_MESSAGE=Update:\ $(git log -1 --pretty=%s)
- git clone -b gh-pages --single-branch https://github.com/materiaalit/tikape-kesa18.git
  build
script:
- bundle exec middleman build
after_success:
- cd build
- git checkout HEAD README.md .github
- git add --all
- git commit -m "$COMMIT_MESSAGE"
- git push "https://hnbot:$GITHUB_API_KEY@github.com/materiaalit/tikape-kesa18.git"
  gh-pages:gh-pages 2>&1 | sed "s/$GITHUB_API_KEY/<confidential>/g"
env:
  global:
    secure: iBf7LRt2cXQno4+7n/TEfk9+sh9Asxs1HayUHzUnofNyoMiE3yzTs4Dqa845J/qKLA7iWN/lsP4B1gfXmJjZ8TxdAGRz9//jSyEwhEr7VG70aPtMoWfxqPnLAhrLjA9jfP+k08Po+tdbB1aWHrwx+Eywbc/+FDvcWZkVIB4WdBWJA7GbTewNVc2JUmT90NNkPvmAm74l/qBteVataPx4Noca4BLCEuAtjoT3CbzQYCXbnp1L6J1LPM5jw7uUOReTA5k59cxU1zzVnWQgHM6aI1DvBZl2rE0JOoS6BcAnGYJmABjiP0cW7i9PfRug4KY4sY8jSVZs/ZOlcvtc+ku+R0/fFL9RZ76EqfpKzYDHWn1jYkIsTAIEpfh6zA37WbBWn67wQd0i9Qb62VrQMPtWwc3kOIAHGUjWrXaTVaByIGFZWBFO+qkAVKT2OEFoVdDeWu809G2bsIZGFAZSNSnejwr/EeGlgBXJbRlJMj+6QmY/KTUZkxJEXnbr4s/QCEkZRkkJ1sWxKZRGA8hOr8bDDXFGMbunp52QiViaCvni1Unm3j0gXyGH7OvXZJticadxZqloWQmtLFBR2LAMEkxtXbQjvMZvu62XIzHQ6SQT+lkBuJMbDdEP695ZCEibtc+XsLcUQ0/52svjAaFdwx4HdZ5zK0TrLiygm9JuVfvChKI=
